import type { Notification, Task, TeamMember, UserProfile } from '@/types';

const getDateOffset = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString().split('T')[0];
};

export const mockTeamMembers: TeamMember[] = [
  {
    id: '1',
    name: 'Sarah Connor',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    role: 'Product Lead',
    projects: 4,
    tasksAssigned: 4,
    completionRate: 92,
    status: 'active',
  },
  {
    id: '2',
    name: 'Alex Rivera',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    role: 'Frontend Engineer',
    projects: 3,
    tasksAssigned: 3,
    completionRate: 85,
    status: 'active',
  },
  {
    id: '3',
    name: 'Marcus Vance',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    role: 'Backend Engineer',
    projects: 5,
    tasksAssigned: 4,
    completionRate: 78,
    status: 'busy',
  },
  {
    id: '4',
    name: 'Elena Rostova',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
    role: 'UI/UX Designer',
    projects: 2,
    tasksAssigned: 2,
    completionRate: 95,
    status: 'active',
  },
  {
    id: '5',
    name: 'David Kim',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    role: 'QA Lead',
    projects: 3,
    tasksAssigned: 1,
    completionRate: 90,
    status: 'offline',
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Migrate to Next.js App Router',
    description: 'Refactor the old directory layout into the app router structure for modern routing.',
    status: 'in-progress',
    priority: 'critical',
    assignedTo: '2',
    dueDate: getDateOffset(2),
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-2',
    title: 'Implement Smart Theme Manager',
    description: 'Add time-based light and dark mode with persisted manual overrides.',
    status: 'completed',
    priority: 'high',
    assignedTo: '2',
    dueDate: getDateOffset(-1),
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-3',
    title: 'Set up Zustand Store Actions',
    description: 'Design global stores for tasks, team members, notifications, and theme state.',
    status: 'completed',
    priority: 'high',
    assignedTo: '3',
    dueDate: getDateOffset(-2),
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-4',
    title: 'Shape Dashboard Analytics',
    description: 'Build reusable Recharts wrappers and feed them dummy weekly performance data.',
    status: 'in-progress',
    priority: 'high',
    assignedTo: '3',
    dueDate: getDateOffset(4),
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-5',
    title: 'Review Dashboard UI System',
    description: 'Polish summary cards, analytics widgets, tables, and team panel layouts.',
    status: 'completed',
    priority: 'medium',
    assignedTo: '4',
    dueDate: getDateOffset(-3),
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-6',
    title: 'Design Component System',
    description: 'Create reusable buttons, dialogs, cards, menus, and shell components.',
    status: 'in-progress',
    priority: 'medium',
    assignedTo: '4',
    dueDate: getDateOffset(3),
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-7',
    title: 'Write Core QA Checklist',
    description: 'Cover routing, theme switching, chart rendering, table actions, and store updates.',
    status: 'pending',
    priority: 'low',
    assignedTo: '5',
    dueDate: getDateOffset(7),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-8',
    title: 'Implement Debounced Search Hook',
    description: 'Create a reusable helper hook for task search controls.',
    status: 'pending',
    priority: 'low',
    assignedTo: '2',
    dueDate: getDateOffset(5),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-9',
    title: 'Optimize Responsive Tables',
    description: 'Keep recent task data readable on compact mobile and tablet screens.',
    status: 'pending',
    priority: 'medium',
    assignedTo: '3',
    dueDate: getDateOffset(6),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-10',
    title: 'Fix Sidebar Drawer Behavior',
    description: 'Resolve mobile drawer toggle behavior and desktop collapse transitions.',
    status: 'overdue',
    priority: 'critical',
    assignedTo: '1',
    dueDate: getDateOffset(-4),
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    type: 'assigned',
    title: 'New Task Assigned',
    message: 'You have been assigned the sidebar drawer polish task.',
    read: false,
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    taskId: 'task-10',
  },
  {
    id: 'notif-2',
    type: 'deadline',
    title: 'Deadline Approaching',
    message: 'The App Router migration task is due in 2 days.',
    read: false,
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    taskId: 'task-1',
  },
  {
    id: 'notif-3',
    type: 'completed',
    title: 'Task Completed',
    message: 'Elena Rostova completed the dashboard UI review.',
    read: true,
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    taskId: 'task-5',
  },
];

export const mockProfile: UserProfile = {
  name: 'Guest User',
  email: '',
  role: 'Guest',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
};
